//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public int Id { get; set; }
        public string Before_Brand { get; set; }
        public string Brand_Name { get; set; }
        public string After_Brand { get; set; }
        public string Background_Image { get; set; }
    }
}
